quarkus:
  application:
    name: ms-naive-bayes-moli
  http:
    port: 8081
  container-image:
    group: ""
    name: ms-naive-bayes-moli
    tag: latest
    registry: franciscoct
  kubernetes:
    namespace: app-datos
  log:
    level: INFO
    file:
      enable: true
      path: ./log/modulo-naive-bayes-moli.log
      level: INFO
      format: '{"log_data":{"fecha":"%d{yyyy-MM-dd HH:mm:ss}","Level":"%-5p","Mensaje":"%m","servicios":[%X{servicios}],"TiempoTotal":%X{tiempo}}}%n'
      rotation:
        max-file-size: 200M
        max-backup-index: 5
        rotate-on-boot: true
        file-suffix: .yyyy-MM-dd
  smallrye-openapi:
    path: /ms-naive-bayes-moli
    info-title: Contrato de Interfaz Microservicio naive-bayes.
    info-version: 1.0.0
    info-description: Contrato de Interfaz para el calculo de naive bayes utilizando los datos del modulo frecuencias y determinar si una cadena es un nombre o apellidos para el modulo de coincidencia de nombres propios.
conexion:
  conexionesdb:
    c3remesas:
      urlbase: x5UVzRH-YVgn2IyG8losupemrKZjogEcKWy7c94m3cc
      endpoint: bXmzk7swyoZ1tjXU4ruFcVB5zMPxXfSzE2mHZ2WLNo7kglEK3CPZTSBn94oKZO32
      name: kEk6Kvs2hKfUgvVTbP47tg
      fsp: hola